image: archlinux
triggers:
  - action: email
    condition: failure
    to: Dmitriy Morozov <dmitriy@mrzv.org>
packages:
  - cmake
  - python
secrets:
  - 51347cbf-5b71-4861-9b85-f92b6deb93b7
sources:
  - git@github.com:mrzv/nesoi
tasks:
  - configure: |
      mkdir nesoi/build
      cd nesoi/build
      cmake ..
  - build: |
      cd nesoi/build
      make
